### PR TITLE
Aggregator/Filter composition via Ids.

### PR DESCRIPTION
**Pull request by awildturtok**

### CODE REVIEW

**Comment by awildturtok** [comment]
@manuel-hegner Please review this.

**Comment by awildturtok** [comment]
This branch is intentionally left to stale, as it will create a lot of friction with the existing codebase. This branch will be merged when development resumes to a less critical period.

**Comment by thoniTUB** [comment]
@awildturtok is this still relevant?

**Comment by awildturtok** [comment]
This is a proposal which would effectively rewrite the entire QueryEngine.

Filters are internally just wrappers around aggregators which is why we could implement them exactly as such in the Query Layer. This would allow more expressiveness in the queries as well as reducing redundancy: At the moment, if a user uses a select and filters on the corresponding filter, the aggregator will be executed twice.

**Pull request closed without merging**
