### PR TITLE
Feature/heroku deploy pipeline

### PR DESCRIPTION
**Pull request by MarcusBaitz**
Now we have a Heroku pipeline. This automatically executes the deployments (`develop` and `master`) after Travis-CI has successfully built.

The deploy script `frontend/scripts/deploy-heroku-docker.sh` is no longer needed.

Because Conquery is not a pure web application, I created a `.heroku.yml`. This will build the docker container of the frontend.

To the Heroku badge: I think that the service is currently not available.

### CODE REVIEW

**Comment by Kadrian** [comment]
Interesting! Could you explain your changes – how / why this works & how this deals with `master` and `develop` branches?

**Comment by Kadrian** [comment]
Cool. Where is the restriction that it only runs on develop / master though? Is there only a single heroku space now? (No conquery-dev anymore?)

**Comment by MarcusBaitz** [comment]
The production (conquery) deploy can work for the master and develop for the staging (conquery-dev). The link to production can be used as a live demo. What do you think about it?

**Comment by Kadrian** [comment]
> The production (conquery) deploy **can** work
What does that mean?

**Comment by manuel-hegner** [comment]
about the badge: it seems the badges were only created in an internal heroku hackathon and is now offline
somebody created an alternative here: https://github.com/gregsadetsky/heroku-ci-badge

**Comment by Kadrian** [comment]
Yes, that's what I linked here: https://github.com/bakdata/conquery/issues/625

**Comment by Kadrian** [comment]
@MarcusBaitz, now @manuel-hegner explained it: You configured the pipeline inside Heroku => Heroku does the branch-matching from now on. 

I'd vote to add a comment to explain this to `heroku.yml`

**Pull request merged**
