### PR TITLE
validity date refactoring

### PR DESCRIPTION
**Pull request by manuel-hegner**
validitydateselection is now its own thing

### CODE REVIEW

**Comment by manuel-hegner** [comment]
With the introduction of selects I want to refactor the validity date selection Before now this was just modeled as a filter so the frontend required no specific handling.

With this PR the table json object has a new field `validityDateSelection` that contains the possible values. The frontend should render this as a single value select where the first given value is already selected and there is no possibility to select no value (this is already supported).

The result should be written in the resulting json object as `validityDate`.

**Comment by Kadrian** [comment]
I agree that this is a good idea, since it's a very important kind of filter.

Now since we have `tables`, `selects`, `filters` and similar wording already, I would like to propose calling this `dateColumn` instead of `validityDate`.

To keep the structure similar to the `filters`, and to be able to use a `defaultValue` I'd like to propose the following.

Table object from the API
``` 
{
  ...
  dateColumn: {
    defaultValue: "ABC",
    options: [
      { value: "ABC", label: "Super date" },
      { value: "EFG", label: "Boring date" },
    ]
  }
}
```

**Table object sent to the API**
```
{
  ...
  dateColumn: {
    value: "ABC"
  }
}
```

**Comment by manuel-hegner** [comment]
Mh, seems reasonable, but can we use `validityDateColumn`? dateColumn alone is not expressing wuite the idea behind this selection.

**Comment by Kadrian** [comment]
=> Haben uns nach reichlicher Diskussion auf `dateColumn` geeinigt :-)

**Comment by manuel-hegner** [comment]
backend part is done

**Comment by Kadrian** [comment]
Frontend part is done as well. Here, like discussed:

Bildschirmfoto 2019-07-05 um 17 40 29

**Pull request merged**
